apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: checkmk
  name: checkmk-csi-prd
  namespace: csi-prd
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: thick-retain-204
